version: 2.1

orbs:
  python: circleci/python@1.2
  docker: circleci/docker@2.1.3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest --pyargs
      - run:
          name: Run Linter
          command: flake8

  docker_deployment:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t user_name/circle_ci_python_example:$CIRCLE_SHA1 .
      - run: docker push user_name/circle_ci_python_example:$CIRCLE_SHA1



workflows:
  Run Tests and Linter:
    jobs:
      - build-and-test
      - docker_deployment:
          requires:
            - build-and-test
