version: 2.1

orbs:
  python: circleci/python@1.2 # The Windows orb gives you everything you need to start using the Windows executor.

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest

workflows:
  my-workflow:
    jobs:
      - build-and-test