version: 2.1

orbs:
  python: circleci/python@3.9

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest
      - run:
          name: Run Linter
          command: flake8

workflows:
  Run Tests:
    jobs:
      - build-and-test