version: 2.1

orbs:
  python: circleci/python@1.2
  docker: circleci/docker@2.1.3

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest --pyargs
      - run:
          name: Run Linter
          command: flake8

  docker_deployment:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deployment of the image to DockerHub
          command: |
            echo $DOCKERHUB_USERNAME
            echo $DOCKERHUB_PASSWORD
            echo $CIRCLE_SHA1
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker build -t $DOCKERHUB_USERNAME/$CIRCLE_SHA1 .
            docker push $DOCKERHUB_USERNAME/python-oc-lettings-fr/$CIRCLE_SHA1:latest



workflows:
  Run Tests and Linter:
    jobs:
      - build-and-test
      - docker_deployment:
          requires:
            - build-and-test
