version: 2.1

orbs:
  python: circleci/python@1.2
  docker: circleci/docker@2.1.3
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest --pyargs
      - run:
          name: Run Linter
          command: flake8

  docker_deployment:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      #password stdin pour evité qu'il soit visible dans les logs ou l'historique du shell
      - run: |
          echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run: docker build -t $DOCKERHUB_USERNAME/python-oc-lettings-fr:$CIRCLE_SHA1 .
      - run: docker push $DOCKERHUB_USERNAME/python-oc-lettings-fr:$CIRCLE_SHA1

  heroku_deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          curl https://cli-assets.heroku.com/install.sh | sh
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a ${HEROKU_APP_NAME} web
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a ${HEROKU_APP_NAME} web



workflows:
  Run Tests and Deploy:
    jobs:
      - build-and-test
      - docker_deployment:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - heroku_deploy:
          requires:
            - build-and-test
            - docker_deployment
          filters:
            branches:
              only: master
