version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest --pyargs
      - run:
          name: Run Linter
          command: flake8

  docker_deployment:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deployment of the image to DockerHub
          command: |
           docker build -t $DOCKER_HUB_USERNAME/python-oc-lettings-fr:$CIRCLE_SHA1 .
           docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_ACCESS_TOKEN
           docker tag $DOCKER_HUB_USERNAME/python-oc-lettings-fr:$CIRCLE_SHA1 $DOCKER_HUB_USERNAME/python-oc-lettings-fr:release
           docker push $DOCKER_HUB_USERNAME/python-oc-lettings-fr:$CIRCLE_SHA1
           docker push $DOCKER_HUB_USERNAME/python-oc-lettings-fr:release



workflows:
  Run Tests and Linter:
    jobs:
      - build-and-test
      - docker_deployment:
          requires:
            - build-and-test
