# Generated by Django 4.0.1 on 2022-12-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
